//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseLabExhibitApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuseLabExhibitApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;gesture&gt;
        ///  &lt;Name&gt;Arms Crossed&lt;/Name&gt;
        ///  &lt;FudgeFactor&gt;0.35&lt;/FudgeFactor&gt;
        ///  &lt;GestureType&gt;0&lt;/GestureType&gt;
        ///  &lt;pose name=&quot;Pose 1&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;TrackXAxis&gt;true&lt;/TrackXAxis&gt;
        ///    &lt;TrackYAxis&gt;true&lt;/TrackYAxis&gt;
        ///    &lt;TrackZAxis&gt;false&lt;/TrackZAxis&gt;
        ///    &lt;DurationMax&gt;10000000&lt;/DurationMax&gt;
        ///    &lt;DurationMin&gt;0&lt;/DurationMin&gt;
        ///    &lt;TrackHead&gt;false&lt;/TrackHead&gt;
        ///    &lt;TrackHipCenter&gt;false&lt;/TrackHipCenter&gt;
        ///    &lt;TrackLeftAnkle&gt;false&lt;/TrackLeftAnkle&gt;
        ///    &lt;TrackLeftElbow&gt;fals [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arms_Crossed {
            get {
                return ResourceManager.GetString("Arms_Crossed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;gesture&gt;
        ///  &lt;Name&gt;Bow LH&lt;/Name&gt;
        ///  &lt;FudgeFactor&gt;0.3&lt;/FudgeFactor&gt;
        ///  &lt;GestureType&gt;0&lt;/GestureType&gt;
        ///  &lt;pose name=&quot;Pose 1&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;TrackXAxis&gt;true&lt;/TrackXAxis&gt;
        ///    &lt;TrackYAxis&gt;true&lt;/TrackYAxis&gt;
        ///    &lt;TrackZAxis&gt;false&lt;/TrackZAxis&gt;
        ///    &lt;DurationMax&gt;10000000&lt;/DurationMax&gt;
        ///    &lt;DurationMin&gt;0&lt;/DurationMin&gt;
        ///    &lt;TrackHead&gt;true&lt;/TrackHead&gt;
        ///    &lt;TrackHipCenter&gt;false&lt;/TrackHipCenter&gt;
        ///    &lt;TrackLeftAnkle&gt;false&lt;/TrackLeftAnkle&gt;
        ///    &lt;TrackLeftElbow&gt;false&lt;/Track [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bow_LH {
            get {
                return ResourceManager.GetString("Bow_LH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;gesture&gt;
        ///  &lt;Name&gt;Bow RH&lt;/Name&gt;
        ///  &lt;FudgeFactor&gt;0.45&lt;/FudgeFactor&gt;
        ///  &lt;GestureType&gt;0&lt;/GestureType&gt;
        ///  &lt;pose name=&quot;Pose 1&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;TrackXAxis&gt;true&lt;/TrackXAxis&gt;
        ///    &lt;TrackYAxis&gt;true&lt;/TrackYAxis&gt;
        ///    &lt;TrackZAxis&gt;false&lt;/TrackZAxis&gt;
        ///    &lt;DurationMax&gt;10000000&lt;/DurationMax&gt;
        ///    &lt;DurationMin&gt;0&lt;/DurationMin&gt;
        ///    &lt;TrackHead&gt;true&lt;/TrackHead&gt;
        ///    &lt;TrackHipCenter&gt;false&lt;/TrackHipCenter&gt;
        ///    &lt;TrackLeftAnkle&gt;false&lt;/TrackLeftAnkle&gt;
        ///    &lt;TrackLeftElbow&gt;false&lt;/Trac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bow_RH {
            get {
                return ResourceManager.GetString("Bow_RH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;gesture&gt;
        ///  &lt;Name&gt;Fox Bow LH&lt;/Name&gt;
        ///  &lt;FudgeFactor&gt;0.4&lt;/FudgeFactor&gt;
        ///  &lt;GestureType&gt;0&lt;/GestureType&gt;
        ///  &lt;pose name=&quot;Pose 1&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;TrackXAxis&gt;true&lt;/TrackXAxis&gt;
        ///    &lt;TrackYAxis&gt;true&lt;/TrackYAxis&gt;
        ///    &lt;TrackZAxis&gt;false&lt;/TrackZAxis&gt;
        ///    &lt;DurationMax&gt;9000000&lt;/DurationMax&gt;
        ///    &lt;DurationMin&gt;0&lt;/DurationMin&gt;
        ///    &lt;TrackHead&gt;true&lt;/TrackHead&gt;
        ///    &lt;TrackHipCenter&gt;false&lt;/TrackHipCenter&gt;
        ///    &lt;TrackLeftAnkle&gt;false&lt;/TrackLeftAnkle&gt;
        ///    &lt;TrackLeftElbow&gt;false&lt;/Tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fox_Bow_LH {
            get {
                return ResourceManager.GetString("Fox_Bow_LH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;gesture&gt;
        ///  &lt;Name&gt;Fox Bow RH&lt;/Name&gt;
        ///  &lt;FudgeFactor&gt;0.2&lt;/FudgeFactor&gt;
        ///  &lt;GestureType&gt;0&lt;/GestureType&gt;
        ///  &lt;pose name=&quot;Pose 1&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;TrackXAxis&gt;true&lt;/TrackXAxis&gt;
        ///    &lt;TrackYAxis&gt;true&lt;/TrackYAxis&gt;
        ///    &lt;TrackZAxis&gt;false&lt;/TrackZAxis&gt;
        ///    &lt;DurationMax&gt;5000000&lt;/DurationMax&gt;
        ///    &lt;DurationMin&gt;0&lt;/DurationMin&gt;
        ///    &lt;TrackHead&gt;true&lt;/TrackHead&gt;
        ///    &lt;TrackHipCenter&gt;false&lt;/TrackHipCenter&gt;
        ///    &lt;TrackLeftAnkle&gt;false&lt;/TrackLeftAnkle&gt;
        ///    &lt;TrackLeftElbow&gt;false&lt;/Tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fox_Bow_RH {
            get {
                return ResourceManager.GetString("Fox_Bow_RH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gotham_Bold {
            get {
                object obj = ResourceManager.GetObject("Gotham_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gotham_Book {
            get {
                object obj = ResourceManager.GetObject("Gotham_Book", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gotham_Light {
            get {
                object obj = ResourceManager.GetObject("Gotham_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;gesture&gt;
        ///  &lt;Name&gt;Hat Tip&lt;/Name&gt;
        ///  &lt;FudgeFactor&gt;0.2&lt;/FudgeFactor&gt;
        ///  &lt;GestureType&gt;0&lt;/GestureType&gt;
        ///  &lt;pose name=&quot;Pose 1&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;TrackXAxis&gt;true&lt;/TrackXAxis&gt;
        ///    &lt;TrackYAxis&gt;true&lt;/TrackYAxis&gt;
        ///    &lt;TrackZAxis&gt;false&lt;/TrackZAxis&gt;
        ///    &lt;DurationMax&gt;5000000&lt;/DurationMax&gt;
        ///    &lt;DurationMin&gt;0&lt;/DurationMin&gt;
        ///    &lt;TrackHead&gt;false&lt;/TrackHead&gt;
        ///    &lt;TrackHipCenter&gt;false&lt;/TrackHipCenter&gt;
        ///    &lt;TrackLeftAnkle&gt;false&lt;/TrackLeftAnkle&gt;
        ///    &lt;TrackLeftElbow&gt;false&lt;/Trac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hat_Tip {
            get {
                return ResourceManager.GetString("Hat_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KlinicSlabBold {
            get {
                object obj = ResourceManager.GetObject("KlinicSlabBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KlinicSlabBoldIt {
            get {
                object obj = ResourceManager.GetObject("KlinicSlabBoldIt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KlinicSlabBook {
            get {
                object obj = ResourceManager.GetObject("KlinicSlabBook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KlinicSlabBookIt {
            get {
                object obj = ResourceManager.GetObject("KlinicSlabBookIt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KlinicSlabLight {
            get {
                object obj = ResourceManager.GetObject("KlinicSlabLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KlinicSlabLightIt {
            get {
                object obj = ResourceManager.GetObject("KlinicSlabLightIt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KlinicSlabMedium {
            get {
                object obj = ResourceManager.GetObject("KlinicSlabMedium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KlinicSlabMediumIt {
            get {
                object obj = ResourceManager.GetObject("KlinicSlabMediumIt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;gesture&gt;
        ///  &lt;Name&gt;Sidestep&lt;/Name&gt;
        ///  &lt;FudgeFactor&gt;0.2&lt;/FudgeFactor&gt;
        ///  &lt;GestureType&gt;0&lt;/GestureType&gt;
        ///  &lt;pose name=&quot;Pose 1&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;TrackXAxis&gt;true&lt;/TrackXAxis&gt;
        ///    &lt;TrackYAxis&gt;true&lt;/TrackYAxis&gt;
        ///    &lt;TrackZAxis&gt;false&lt;/TrackZAxis&gt;
        ///    &lt;DurationMax&gt;5000000&lt;/DurationMax&gt;
        ///    &lt;DurationMin&gt;0&lt;/DurationMin&gt;
        ///    &lt;TrackHead&gt;false&lt;/TrackHead&gt;
        ///    &lt;TrackHipCenter&gt;true&lt;/TrackHipCenter&gt;
        ///    &lt;TrackLeftAnkle&gt;false&lt;/TrackLeftAnkle&gt;
        ///    &lt;TrackLeftElbow&gt;false&lt;/Trac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sidestep {
            get {
                return ResourceManager.GetString("Sidestep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;gesture&gt;
        ///  &lt;Name&gt;Snaps&lt;/Name&gt;
        ///  &lt;FudgeFactor&gt;0.5000001&lt;/FudgeFactor&gt;
        ///  &lt;GestureType&gt;0&lt;/GestureType&gt;
        ///  &lt;pose name=&quot;Pose 1&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;TrackXAxis&gt;true&lt;/TrackXAxis&gt;
        ///    &lt;TrackYAxis&gt;true&lt;/TrackYAxis&gt;
        ///    &lt;TrackZAxis&gt;false&lt;/TrackZAxis&gt;
        ///    &lt;DurationMax&gt;8000000&lt;/DurationMax&gt;
        ///    &lt;DurationMin&gt;0&lt;/DurationMin&gt;
        ///    &lt;TrackHead&gt;false&lt;/TrackHead&gt;
        ///    &lt;TrackHipCenter&gt;false&lt;/TrackHipCenter&gt;
        ///    &lt;TrackLeftAnkle&gt;false&lt;/TrackLeftAnkle&gt;
        ///    &lt;TrackLeftElbow&gt;false&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Snaps {
            get {
                return ResourceManager.GetString("Snaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;gesture&gt;
        ///  &lt;Name&gt;Swing Snaps&lt;/Name&gt;
        ///  &lt;FudgeFactor&gt;0.5500001&lt;/FudgeFactor&gt;
        ///  &lt;GestureType&gt;0&lt;/GestureType&gt;
        ///  &lt;pose name=&quot;Pose 1&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;TrackXAxis&gt;true&lt;/TrackXAxis&gt;
        ///    &lt;TrackYAxis&gt;true&lt;/TrackYAxis&gt;
        ///    &lt;TrackZAxis&gt;false&lt;/TrackZAxis&gt;
        ///    &lt;DurationMax&gt;12000000&lt;/DurationMax&gt;
        ///    &lt;DurationMin&gt;0&lt;/DurationMin&gt;
        ///    &lt;TrackHead&gt;false&lt;/TrackHead&gt;
        ///    &lt;TrackHipCenter&gt;false&lt;/TrackHipCenter&gt;
        ///    &lt;TrackLeftAnkle&gt;false&lt;/TrackLeftAnkle&gt;
        ///    &lt;TrackLeftElbow&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Swing_Snaps {
            get {
                return ResourceManager.GetString("Swing_Snaps", resourceCulture);
            }
        }
    }
}
